### ISSUE TITLE
Remap some of the OMM Cause and Impact codes

### ISSUE THREAD

**Issue by paasovaara** [HSLdevcom/transitdata-omm-alert-source#2]
TODO add here all that needs to be changed.

current mapping is here: 
https://hsldevcom.slack.com/files/U4CJ5K7L1/FE7SB1JHG/alustava_omm_-__gtfs_realtime_-mappays.txt

official source:
https://developers.google.com/transit/gtfs-realtime/reference/#enum_effect
https://developers.google.com/transit/gtfs-realtime/reference/#enum_cause

**Comment by samijuhani** [comment]
entity {
  id: "5659"
Poikkeusaikataulu -> effect: SIGNIFICANT_DELAYS should be additional_service or something else?

**Comment by samijuhani** [comment]
entity {
  id: "5719"
entity {
  id: "5723"
Poikkeukset mahdollisia -> effect: SIGNIFICANT_DELAYS tbc

**Comment by samijuhani** [comment]
entity {
  id: "5723"
entity {
  id: "5667"
Mahdollisesti myöhässä -> effect: OTHER_EFFECT tbc
